name: Conformance End-To-End Tests

on:
  pull_request:

# Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-cosmos-examples:
    name: test-cosmos-examples
    runs-on: ubuntu-latest
    steps:
      # Install and setup go
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: checkout interchaintest
        uses: actions/checkout@v4

      # cleanup environment on self-hosted test runner
      - name: clean
        run: |-
          rm -rf ~/.interchaintest

      # run tests
      - name: run example cosmos tests
        run: go test -race -failfast -timeout 30m -v -p 2 ./examples/cosmos
