name: Run Go Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'

jobs:
  test:
    name: tests
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: checkout ibctest
        uses: actions/checkout@v2

      # cleanup docker environment on self-hosted test runner
      # - name: prepare fresh docker environment
      #   run: |
      #     docker stop $(docker ps -a -q) || true
      #     docker rm -f $(docker ps -a -q) || true
      #     docker network prune -f || true

      # cleanup environment on self-hosted test runner
      - name: clean
        run: -|
          rm -rf ~/.ibctest

      # run tests
      - name: run all tests
        # show cosmos chain and relayer logs on test failure
        run: (go test -timeout 30m -v -p 2 ./...) || (echo "\n\n*****CHAIN and RELAYER LOGS*****" && cat "$HOME/.ibctest/logs/ibctest.log" && exit 1)
