name: Run Go Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'

jobs:
  test:
    name: tests
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout ibctest
        uses: actions/checkout@v2

      # cleanup environment on self-hosted test runner
      - name: clean
        run: |-
          rm -rf ~/.ibctest

      # run tests
      - name: run all tests
        # show cosmos chain and relayer logs on test failure
        run: (go test -race -timeout 30m -v -p 2 ./...) || (echo "\n\n*****CHAIN and RELAYER LOGS*****" && cat "$HOME/.ibctest/logs/ibctest.log" && exit 1)
  test-cosmos:
    name: test-cosmos
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout ibctest
        uses: actions/checkout@v2

      # cleanup environment on self-hosted test runner
      - name: clean
        run: |-
          rm -rf ~/.ibctest

      # run tests
      - name: run all tests
        run: cd examples/cosmos && go test -race -timeout 30m -v -p 2 ./...
