name: Run Go Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'

jobs:
  test-unit:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      # Install and setup go
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout ibctest
        uses: actions/checkout@v2

      # cleanup environment on self-hosted test runner
      - name: clean
        run: |-
          rm -rf ~/.ibctest

      # run tests
      - name: run unit tests
        run: go test -race -timeout 30m -v -p 2 ./...
  test-cmd-ibctest:
    name: test-cmd-ibctest
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout ibctest
        uses: actions/checkout@v2

      # cleanup environment on self-hosted test runner
      - name: clean
        run: |-
          rm -rf ~/.ibctest

      # run tests
      - name: run conformance tests
        run: (cd cmd/ibctest && go test -race -timeout 30m -v -p 2 ./...) || (echo "\n\n*****CHAIN and RELAYER LOGS*****" && cat "$HOME/.ibctest/logs/ibctest.log" && exit 1)
  test-ibc-examples:
    name: test-ibc-examples
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout ibctest
        uses: actions/checkout@v2

      # cleanup environment on self-hosted test runner
      - name: clean
        run: |-
          rm -rf ~/.ibctest

      # run tests
      - name: run example ibc tests
        run: cd examples/ibc && go test -race -timeout 30m -v -p 2 ./...
  test-cosmos-examples:
    name: test-cosmos-examples
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout ibctest
        uses: actions/checkout@v2

      # cleanup environment on self-hosted test runner
      - name: clean
        run: |-
          rm -rf ~/.ibctest

      # run tests
      - name: run example cosmos tests
        run: cd examples/cosmos && go test -race -timeout 30m -v -p 2 ./...
