name: Run Unit Tests

on:
  pull_request:

# Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    name: unit-tests
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: checkout interchaintest
        uses: actions/checkout@v3

      # run tests
      - name: run unit tests
        # -short flag purposefully omitted because there are some longer unit tests
        run: go test -race -timeout 10m -failfast -p 2 $(go list ./... | grep -v /cmd | grep -v /examples)
