name: Run Unit Tests

on:
  pull_request:

jobs:
  test-unit:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      # Install and setup go
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: checkout interchaintest
        uses: actions/checkout@v3

      # run tests
      - name: run unit tests
        # -short flag purposefully omitted because there are some longer unit tests
        run: go test -race -timeout 10m -failfast -p 2 $(go list ./... | grep -v /cmd | grep -v /examples)